tasks:
  - init: sudo apt update -y && sudo apt upgrade -y && rustup default nightly && rustup target add wasm32-unknown-unknown && npm install -g npm@8.19.2 wrangler@latest && curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    command: wrangler publish --dry-run --outdir=dist


