compatibility_date = "2022-01-20"
main = "./build/worker/shim.mjs"
name = "pzzld-worker"
workers_dev = true

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[vars]
WORKERS_RS_VERSION = "0.0.12"
