name: Deploy

on:
  push:
    branches: [ "main", "master", "prod" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * 5"
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  deploy:
#     if: ${{ github.event.inputs.publish }}
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
